//for customerOverview
export const customerPortfolio = "Client Portfolio";
export const recentTrends = "Recent Trends";
export const demographic = "Demographic";
export const riskDistribution = "Risk Distribution";
export const assetAllocationAnomaly = "Asset Allocation Anomaly";
export const heldAwayInvestment = "Held Away Investment";
export const topWalletContributors = "Top Wallet Contributors";
export const topRevenueContributors = "Top Revenue Contributors";

export const ASSET_ALLOCATION_DATA = [
  {
    "H/A": "A",
    Team: "Torino",
    Allocation: 0.62,
    "Risk Score": 10,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Atalanta",
    Allocation: 2.35,
    "Risk Score": 23,
    Result: "Mutual Fund",
  },
  {
    "H/A": "A",
    Team: "Milan",
    Allocation: 1.89,
    "Risk Score": 26,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Chievo",
    Allocation: 1.4,
    "Risk Score": 13,
    Result: "Mutual Fund",
  },
  {
    "H/A": "A",
    Team: "Bologna",
    Allocation: 1.02,
    "Risk Score": 11,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Frosinone",
    Allocation: 0.56,
    "Risk Score": 11,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Lazio",
    Allocation: 1.01,
    "Risk Score": 16,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Empoli",
    Allocation: 1.56,
    "Risk Score": 20,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Spal",
    Allocation: 1.8,
    "Risk Score": 6,
    Result: "Stocks",
  },
  {
    "H/A": "A",
    Team: "Napoli",
    Allocation: 2.49,
    "Risk Score": 26,
    Result: "Mutual Fund",
  },
  {
    "H/A": "A",
    Team: "Fiorentina",
    Allocation: 1.3,
    "Risk Score": 14,
    Result: "Mutual Fund",
  },
  {
    "H/A": "H",
    Team: "Sampdoria",
    Allocation: 1.2,
    "Risk Score": 8,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Udinese",
    Allocation: 1.22,
    "Risk Score": 9,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Inter",
    Allocation: 2.68,
    "Risk Score": 17,
    Result: "Mutual Fund",
  },
  {
    "H/A": "A",
    Team: "Cagliari",
    Allocation: 2.1,
    "Risk Score": 16,
    Result: "Mutual Fund",
  },
  {
    "H/A": "H",
    Team: "Genoa",
    Allocation: 1.84,
    "Risk Score": 15,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Juventus",
    Allocation: 2.12,
    "Risk Score": 20,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Sassuolo",
    Allocation: 0.72,
    "Risk Score": 10,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Parma",
    Allocation: 0.58,
    "Risk Score": 6,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Torino",
    Allocation: 1.87,
    "Risk Score": 10,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Atalanta",
    Allocation: 2.68,
    "Risk Score": 23,
    Result: "Mutual Fund",
  },
  {
    "H/A": "H",
    Team: "Milan",
    Allocation: 0.85,
    "Risk Score": 8,
    Result: "Mutual Fund",
  },
  {
    "H/A": "A",
    Team: "Chievo",
    Allocation: 0.84,
    "Risk Score": 16,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Bologna",
    Allocation: 2.69, //fieldPer
    "Risk Score": 20, //Risk Sc
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Frosinone",
    Allocation: 1.51,
    "Risk Score": 11,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Lazio",
    Allocation: 1.77,
    "Risk Score": 13,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Empoli",
    Allocation: 0.14,
    "Risk Score": 5,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "Real Madrid",
    Allocation: 3.58,
    "Risk Score": 30,
    Result: "GI",
  },
  {
    "H/A": "H",
    Team: "Viktoria Plzen",
    Allocation: 0.33,
    "Risk Score": 7,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "CSKA Moscow",
    Allocation: 0.73,
    "Risk Score": 13,
    Result: "Debt Fund",
  },
  {
    "H/A": "A",
    Team: "CSKA Moscow",
    Allocation: 1.1,
    "Risk Score": 14,
    Result: "Debt Fund",
  },
  {
    "H/A": "H",
    Team: "Real Madrid",
    Allocation: 1.87,
    "Risk Score": 12,
    Result: "Stocks",
  },
  {
    "H/A": "A",
    Team: "Viktoria Plzen",
    Allocation: 1.85,
    "Risk Score": 13,
    Result: "Stocks",
  },
  {
    "H/A": "A",
    Team: "Porto",
    Allocation: 3.71,
    "Risk Score": 31,
    Result: "Stocks",
  },
  {
    "H/A": "H",
    Team: "Porto",
    Allocation: 0.56,
    "Risk Score": 7,
    Result: "Hello",
  },
];
